spring:
  profiles:
    active: dev
---
server:
  port:
spring:
  profiles: dev
  application:
    name: microservice-config-dev
---
server:
  port: 4002
spring:
  profiles: prod
  application:
    name: microservice-config-prod
